### ISSUE TITLE
さらに内容を見させてもらいました。

### ISSUE THREAD

**Issue by Kiyoshi-Tajima** [t-kazari/2020_application_repoitory#2]
各定義書を拝見させていただき、内容はさておき
「要点」はついていると思います、継続して続けてください。

さてさて、アーキのほうですが
これ「SpringBoot」って。。。いる？ｗ
やろうと思いえばFirebase内におさまりそうなところ

ただ、面白そうなんで思うがままやってみてください。

**Comment by t-kazari** [comment]
見てくださりありがとうございます。
確かにFirebaseCloudFunctionを用いればサーバサイド処理を行うことができると思うのですが、目標管理にも挙げたJavaでの開発修行およびGCPの取り扱いスキル向上のためにも、サーバサイドでPaaSであるGoogleAppEngine(standard環境)を用いようと考えております。
とりあえずいろいろ試しながらやってみたいと思います。

**Comment by Kiyoshi-Tajima** [comment]
そうだったね、ついつい「こうした方が」思ってしまいました。
いろいろ試してください、やってもらうことでこちらも新たな「発見」ができると
思っています、楽しみにしてます。
